services:
  web:
    image: nginx:1.15.6
    container_name: crud_web
    ports:
      - "8000:80"
    volumes:
      - ./crud-app:/var/www/html
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - crud_network

  app:
    build:
      context: ./docker/app
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: crud_app
    volumes:
      - ./crud-app:/var/www/html
    depends_on:
      - mysql
    networks:
      - crud_network
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: crud_mysql
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - crud_network

networks:
  crud_network:
    driver: bridge

volumes:
  mysql_data:
